### PR TITLE
changed rules to a list of keys for proper ingestion by cg-snort-bosh…

### PR DESCRIPTION
**Pull request by datn**
…release

### CODE REVIEW

**Comment by datn** [comment]
My newly installed yamllint went to town on logsearch-jobs.yml, highlighting a zillion indentation errors that go way beyond the few changes I made, so *shrug* we'll see if it works.

**Comment by cnelson** [comment]
If you want to test this you can download the secrets and run the generate script locally first.

**Comment by datn** [comment]
Well, generate did output a manifest that is just as right- or wrong-looking as the source files, without spruce error.

**Comment by datn** [comment]
I pointed staging at my branch and built successfully:

https://ci.fr.cloud.gov/teams/main/pipelines/deploy-logsearch/jobs/deploy-logsearch-staging/builds/77

**Comment by datn** [comment]
Tested with a couple of curl calls from cluster_monitor (the exempt host) and the elasticsearch_master itself. Call showed up when running strings on the snort-lo log (for the elasticsearch master itself) and not when running strings on the snort-eth0 log (for the remote cluster monitor), suggesting the "suppress" lines are working.

**Pull request merged**
